In [13]:
import torch

# Type hints.
from typing import List, Tuple
from torch import Tensor


In [14]:
x = torch.arange(24)
print(x)

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
        18, 19, 20, 21, 22, 23])


In [15]:
y = x.view(3, 2, 4)
print(y)

tensor([[[ 0,  1,  2,  3],
         [ 4,  5,  6,  7]],

        [[ 8,  9, 10, 11],
         [12, 13, 14, 15]],

        [[16, 17, 18, 19],
         [20, 21, 22, 23]]])


In [16]:
print(y[0][0])
print(y[0][1])
print(y[1][0])
print(y[1][1])
print(y[2][0])
print(y[2][1])


tensor([0, 1, 2, 3])
tensor([4, 5, 6, 7])
tensor([ 8,  9, 10, 11])
tensor([12, 13, 14, 15])
tensor([16, 17, 18, 19])
tensor([20, 21, 22, 23])


In [17]:
part1 = y[0][0]
part2 = y[0][1]
part3 = y[1][0]
part4 = y[1][1]
part5 = y[2][0]
part6 = y[2][1]

y = torch.cat((part1, part4, part2, part5, part3, part6), 0)

y=y.reshape(3,8)
#part1,part2
#part3, part4
#part5, part6
# we want 
#part1, part4,
#part2, part5, 
#part3, part6
print(y)

tensor([[ 0,  1,  2,  3, 12, 13, 14, 15],
        [ 4,  5,  6,  7, 16, 17, 18, 19],
        [ 8,  9, 10, 11, 20, 21, 22, 23]])


In [18]:

#y[0][1] = part4


In [19]:
print(y)

tensor([[ 0,  1,  2,  3, 12, 13, 14, 15],
        [ 4,  5,  6,  7, 16, 17, 18, 19],
        [ 8,  9, 10, 11, 20, 21, 22, 23]])


In [20]:
x = torch.tensor([
          [10, 20, 30],
          [ 2,  5,  1]])

In [21]:
y = x.clone()

row_min_vals, row_min_idxs = y.min(dim=1)

print(row_min_vals)

tensor([10,  1])


In [22]:
print(row_min_idxs)

tensor([0, 2])


In [23]:
row_indices = torch.arange(y.size(0)) 
y[row_indices, row_min_idxs] = 0
print(y)

tensor([[ 0, 20, 30],
        [ 2,  5,  0]])


In [24]:
# We will add the vector v to each row of the matrix x,
# storing the result in the matrix y
x = torch.tensor([[1,2,3], [4,5,6], [7,8,9], [10, 11, 12]])
v = torch.tensor([1, 0, 1])
y = x + v  # Add v to each row of x using broadcasting
print(y)

tensor([[ 2,  2,  4],
        [ 5,  5,  7],
        [ 8,  8, 10],
        [11, 11, 13]])


In [ ]:
x = torch.tensor([[0., 30., 600.], 
                  [1., 10., 200.], [
                    -1., 20., 400.]])

mu_j = x.sum(dim=0) / x.shape[0]
print(mu_j)

tensor([  0.,  20., 400.])
